### PR TITLE
Changed the use of "firmware" to more conventional "software"

### PR DESCRIPTION
**Pull request by randym32**
Great project! As someone who still is on WinForms (and loving it), I hope someday to see how you did the UI in WPF.

I changed the use of "firmware" to "software" to be more consistent.  Only a couple of tiny parts of Vector are called firmware -- the cube firmware and the body board firmware.

### CODE REVIEW

**Comment by cyb3rdog** [comment]
Hi Randy, first of all many thanks for your interrest in this project. I am truly honored my friend.
I really highly appretiate that you have taken your time and looked to this, and as me being non native english speaker, I am really quite surprised, that this is the only mistake you found in my texts :)
However, I have chosen the term 'firmware' quite intentionally, as for the majority of the users, this will more preciselly describe of what they can expect... 
The stage III is in fact really going to eventually be the full oskr firmware ota release with codelab (and another support software) included on Vector's file system. And because the OTA's, and generally, the whole software packs driving any device, are altoghether considered firmware, i will with all respect stick with using the word firmware here.
However, thanks a lot for your contribution, and if you'll find anything else you'll think I could improve, please do not hesitate to let me know, as this pr from you made my day!
Thanks Randy, stay in touch!
Cheers!

**Comment by randym32** [comment]
I respectfully disagree about both the expectations and definitions.  Firmware has a technical classification, and very restrictive expectation.  It has very limited functionality by its nature and controls the hardware at a lower level.  Firmware is fixed and executed from flash, not loaded from a secondary source; modifying or changing a firmware application requires fully restarting its hardware.

Vector’s software is not firmware, is standard linux software, held in a secondary store in a complex format,  loaded with complex dynamic linking processes and an executed from RAM.  It can and does run on OS X and linux.

The OTA only contains 32KB  firmware.   It contains the software updates and resources.  It is not conventional for OTA to be “generally” considered firmware; it is an update file not firmware at all.  (Nor is it a “ROM” as some android users fancifully call it.)   Vectors creators were consistent in calling it a software update.

Have a great day!
Randy
 — Sent unencumbered by the thought process

**Comment by cyb3rdog** [comment]
Ok Randy, i'll change it :)

My whole point here was to explain this goal as simply as possible to the ordinary Vector users, where 99 % of them refers and understands the terms updates and OSKR as a firmware, whether we like ir or not.

So for being correct, I will reopen and merge your PR, but stay alert. once the first non-technical mom or a kid will ask whether the codelab ota is firmware update or not, I will redirect them to you to explain :D ( just kidding, i won't do that )...

But to actually follow up in this nice exchange of views, I still belive that the term firmware is applicable here, as from its basic definition, firmware is just a piece of software flashed onto the device's chips, mostly to the ROM. So doesn't this apply to most of the used linux system partitions there? Only the userdata and some temps are read/write by default, all other partitions has to be remounted in order to make them r/w. That is a real fail save approach for firmwares to not break, being able to recover from criticals with simple reboot.
Vector and its creators aside, take a look at any other arm devices, once they update and flash their soc, they're calling it firmware update, bundling the low level hw embedded software, with the OS into this term altogheter. 

You too have a great day Randy!
Cheers,
Vaclav

**Comment by randym32** [comment]
Good evening (or morning)!

I agree very much being understandable by people, and reducing the language confusion.   I see using the terms consistently with Vector internal design, and among people in the community is an important part of that.

I anticipate that lots of support challenges in language, concepts and technical stuff once more people dig into the source code, behavior tree and animation files.  (They can do the later two now, but will have more options soon.)  There are a lot of terms, (which are consistent with the video game and animation fields as far I as can tell), are not familiar to those outside of video game development.  Vectors “animation” resources have half a dozen or so specific kinds of animation.  The AI system where it get more confusing: it  has behaviors, behavior ID, behavior Class, behavior tree, user intent, cloud intent, system intent, app intent, actions, and a few other things.

New comers will probably overwhelmed by the distinctions and the unusual terms -- along with the some accidental misuses. And confused by the different way of thinking it will take to modify Vector’s brain.   (It doesn’t help that the escape pod team used the terms “behavior” and “intent” to mean different things from what Vector means... that is going to cause confusion later as people try to create their own custom Vector behaviors and intents on Vector and try to modify the EscapePod to keep up.)

> firmware is just a piece of software flashed onto the device's chips, mostly to the ROM. So doesn’t this apply to most of the used linux system partitions there?

Firmware is in ROM, EEPROM or flash.. or (less commonly) RAM .  But that is because firmware has a direct relationship with interacting with the hardware, and is run from the primary store (main memory).  The processor runs it without loading, translations or steps to change the instructions before the processor can use it, or provide virtualization steps.  (This is often called running on “bare metal”)

Lets consider a laptop it used to be a hard drive, but is now a flash based SSD.  But the way the OS/applications are run are just like they were on the hard drive; both are still secondary stores.   The OS X/Windows/Linux & applications are 
Held in a complex file system
In a complex dynamic linked format
Have to be loaded into RAM, and linked there
Executed from the RAM
The file system can technically be modified on the fly (The program can be changed without having to restart the hardware)
The program does not interact with the hardware or peripheral control registers; it uses a subset of the processor instructions, permissions, and uses sophisticated features of the OS and device drivers 
The programs execute in a virtual memory environment, not just for security, but to also allow for emulating more RAM than is present
The more of those items there are, the more likely it isn’t firmware.  Item #1 is the one that most makes the OS/applications not firmware.  I’d say #5 & #6  & #7 are the next most important item, followed by the rest.  The more intermediation to allow the code to run and separate it from hardware, the better it is described as software. 

The partitions are mounted as readonly by default but that is from a good unix practice to protect the mutable system.. but it isn’t a ROM, just an OS convenience.   Firmware has similar practice, and further reasons that program-flash is rarely modified.  The program-flash that holds firmware is hard to update, because of the flash technology, the CPU integration (modifying the program flash requires the CPU to lock until the slow erase cycle completes),  and then to help people like me who require the flash to be protected against modification.  The firmware program-flash modifications take a special program and procedures to modify, while updating the linux programs can happen piecemeal using common file system access.

(Developer mode -- enabling write-mode -- is going to be more common in OSKR vectors due to the changing and tweaking of the implementation to support development cycle, and complex customizations. This doesn’t require a full hardware reboot, just starting and stopping a couple of “vic” processes.)


> take a look at any other arm devices, once they update and flash their soc, they’re calling it firmware update

This differs from my experience. I work a lot with the ARM devices (I work in embedded), and it has been partitioned as:
anything in Cortex-M or Cortex-R running in program flash or the ROM (masked in) is firmware.
In the Cortex-A, the items in the ROM (the BIOS-like stuff) and its program Flash is firmware, which includes the first stage boot loader.  Key BIOS drivers are loaded into RAM (or executed in place) and are often referred to either as device firmware, applets or trustlets.  The stuff after the bootloader -- usually with a sophisticated OS like linux -- runs in RAM and has been called application software.  That’s because it is  like the laptop OS earlier, pulled in from a secondary storage.
Android and Apple (among the two biggest users of Cortex-As) both refer to this as software updates, at least in experience.  For example, from android.com “Android devices in the field can receive and install over-the-air (OTA) updates to the system, application software, and time zone rule”

I find that Android sites have made an effort to try to explain the difference, and give a mental picture for people:
https://www.androidauthority.com/firmware-vs-software-1005643 <https://www.androidauthority.com/firmware-vs-software-1005643>

On ARM.com <http://arm.com/> they have their site organized around firmware for the low level (“bare metal”) and software for the applications, and  refer to 
https://www.reviewsed.com/firmware-vs-embedded-software/ <https://www.reviewsed.com/firmware-vs-embedded-software/>  when the question comes up in the forums. 


Thank-you and have a great day!
Randy
 — Sent unencumbered by the thought process

**Comment by cyb3rdog** [comment]
Hi Randy,
thank you for your time on elaborating on this.

I do fully agree that calling things the right name is important, especially among us and escpecially in any kind of documentation. And yes, I do admit that misusing the terms is never right thing to do, which was actually the reason, why I have re-evaluated my decision from having this let say more end-user oriented, and allow this misuse, to having it correct in first place with correct conventional naming. So eventually, I will be rewriting this in more places..

Thanks again!
Cheers,
Vaclav

**Pull request merged**
